require "user.plugins"
require "user.keymap"
require "user.colorscheme"
require "user.options"
require "user.lsp"
require "user.nvim-cmp"
require "user.bufferline"
require "user.treesitter"
require "user.comment"
require "user.lualine"
require "user.autopairs"
require "user.gitsigns"
require "user.bufferline"
require "user.nvim-tree"

