require "user.integrations.vimnotify"
require "user.integrations.autopairs"
require "user.integrations.bufferline"
require "user.integrations.colorscheme"
require "user.integrations.comment"
require "user.integrations.gitsigns"
require "user.integrations.hop"
require "user.integrations.illuminate"
require "user.integrations.indentline"
require "user.integrations.lualine"
require "user.integrations.nvim-tree"
require "user.integrations.toggleterm"
require "user.integrations.treesitter"
require "user.integrations.vimtex"
require "user.integrations.whichkey"

