---@class icons
---@field kind kind
---@field git git
---@field ui ui
---@field diagnostics diagnostics
---@field misc misc
---@field signs signs
return {
    ---@class kind
    ---@field Array string
    ---@field Boolean string
    ---@field Class string
    ---@field Color string
    ---@field Constant string
    ---@field Constructor string
    ---@field Enum string
    ---@field EnumMember string
    ---@field Event string
    ---@field Field string
    ---@field File string
    ---@field Folder string
    ---@field Function string
    ---@field Interface string
    ---@field Key string
    ---@field Keyword string
    ---@field Method string
    ---@field Module string
    ---@field Namespace string
    ---@field Null string
    ---@field Number string
    ---@field Object string
    ---@field Operator string
    ---@field Package string
    ---@field Property string
    ---@field Reference string
    ---@field Snippet string
    ---@field String string
    ---@field Struct string
    ---@field Text string
    ---@field TypeParameter string
    ---@field Unit string
    ---@field Value string
    ---@field Variable string
    kind = {
        Array = "",
        Boolean = "",
        Class = "",
        Color = "",
        Constant = "",
        Constructor = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "",
        File = "",
        Folder = "",
        Function = "",
        Interface = "",
        Key = "",
        Keyword = "",
        Method = "",
        Module = "",
        Namespace = "",
        Null = "ﳠ",
        Number = "",
        Object = "",
        Operator = "",
        Package = "",
        Property = "",
        Reference = "",
        Snippet = "",
        String = "",
        Struct = "",
        Text = "",
        TypeParameter = "",
        Unit = "",
        Value = "",
        Variable = "",
    },
    ---@class git
    ---@field LineAdded string
    ---@field LineModified string
    ---@field LineRemoved string
    ---@field FileDeleted string
    ---@field FileIgnored string
    ---@field FileRenamed string
    ---@field FileStaged string
    ---@field FileUnmerged string
    ---@field FileUnstaged string
    ---@field FileUntracked string
    ---@field Diff string
    ---@field Repo string
    ---@field Octoface string
    ---@field Branch string
    git = {
        LineAdded = "",
        LineModified = "",
        LineRemoved = "",
        FileDeleted = "",
        FileIgnored = "◌",
        FileRenamed = "",
        FileStaged = "S",
        FileUnmerged = "",
        FileUnstaged = "",
        FileUntracked = "U",
        Diff = "",
        Repo = "",
        Octoface = "",
        Branch = "",
    },
    ---@class ui
    ---@field LanguageServer string
    ---@field HoverSource string
    ---@field FormatterSource string
    ---@field DiagnosticsSource string
    ---@field CodeActionSource string
    ---@field ArrowCircleDown string
    ---@field ArrowCircleLeft string
    ---@field ArrowCircleRight string
    ---@field ArrowCircleUp string
    ---@field BoldArrowDown string
    ---@field BoldArrowLeft string
    ---@field BoldArrowRight string
    ---@field BoldArrowUp string
    ---@field BoldClose string
    ---@field BoldCircleDividerLeft string
    ---@field BoldCircleDividerRight string
    ---@field BoldDividerLeft string
    ---@field BoldDividerRight string
    ---@field BoldLineLeft string
    ---@field BookMark string
    ---@field BoxChecked string
    ---@field Bug string
    ---@field Stacks string
    ---@field Scopes string
    ---@field Watches string
    ---@field DebugConsole string
    ---@field Calendar string
    ---@field Check string
    ---@field ChevronRight string
    ---@field ChevronShortDown string
    ---@field ChevronShortLeft string
    ---@field ChevronShortRight string
    ---@field ChevronShortUp string
    ---@field Circle string
    ---@field Close string
    ---@field CloudDownload string
    ---@field Code string
    ---@field Comment string
    ---@field Dashboard string
    ---@field DividerLeft string
    ---@field DividerRight string
    ---@field DoubleChevronRight string
    ---@field Ellipsis string
    ---@field EmptyFolder string
    ---@field EmptyFolderOpen string
    ---@field File string
    ---@field FileSymlink string
    ---@field Files string
    ---@field FindFile string
    ---@field FindText string
    ---@field Fire string
    ---@field Folder string
    ---@field FolderOpen string
    ---@field FolderSymlink string
    ---@field Forward string
    ---@field Gear string
    ---@field History string
    ---@field Lightbulb string
    ---@field LineLeft string
    ---@field LineMiddle string
    ---@field List string
    ---@field Lock string
    ---@field NewFile string
    ---@field Note string
    ---@field Package string
    ---@field Pencil string
    ---@field Plus string
    ---@field Project string
    ---@field Search string
    ---@field SignIn string
    ---@field SignOut string
    ---@field SmallDot string
    ---@field Tab string
    ---@field Table string
    ---@field Target string
    ---@field Telescope string
    ---@field Text string
    ---@field Tree string
    ---@field Triangle string
    ---@field TriangleShortArrowDown string
    ---@field TriangleShortArrowLeft string
    ---@field TriangleShortArrowRight string
    ---@field TriangleShortArrowUp string
    ---@field MoonOne string
    ---@field MoonTwo string
    ---@field MoonThree string
    ---@field MoonFour string
    ---@field MoonFive string
    ---@field MoonSix string
    ---@field MoonSeven string
    ---@field MoonEight string
    ui = {
        LanguageServer = "",
        HoverSource = "",
        FormatterSource = "󰉠",
        DiagnosticsSource = "󰨯",
        CodeActionSource = "󱉂",
        ArrowCircleDown = "",
        ArrowCircleLeft = "",
        ArrowCircleRight = "",
        ArrowCircleUp = "",
        BoldArrowDown = "",
        BoldArrowLeft = "",
        BoldArrowRight = "",
        BoldArrowUp = "",
        BoldClose = "",
        BoldDividerLeft = "",
        BoldDividerRight = "",
        BoldCircleDividerLeft = "",
        BoldCircleDividerRight = "",
        BoldLineLeft = "▎",
        BookMark = "",
        BoxChecked = "",
        Bug = "",
        Stacks = "",
        Scopes = "",
        Watches = "",
        DebugConsole = "",
        Calendar = "",
        Check = "",
        ChevronRight = ">",
        ChevronShortDown = "",
        ChevronShortLeft = "",
        ChevronShortRight = "",
        ChevronShortUp = "",
        Circle = "",
        Close = "",
        CloudDownload = "",
        Code = "",
        Comment = "",
        Dashboard = "",
        DividerLeft = "",
        DividerRight = "",
        DoubleChevronRight = "»",
        Ellipsis = "",
        EmptyFolder = "",
        EmptyFolderOpen = "",
        File = "",
        FileSymlink = "",
        Files = "",
        FindFile = "",
        FindText = "",
        Fire = "",
        Folder = "",
        FolderOpen = "",
        FolderSymlink = "",
        Forward = "",
        Gear = "",
        History = "",
        Lightbulb = "",
        LineLeft = "▏",
        LineMiddle = "│",
        List = "",
        Lock = "",
        NewFile = "",
        Note = "",
        Package = "",
        Pencil = "",
        Plus = "",
        Project = "",
        Search = "",
        SignIn = "",
        SignOut = "",
        SmallDot = "",
        Tab = "",
        Table = "",
        Target = "",
        Telescope = "",
        Text = "",
        Tree = "",
        Triangle = "契",
        TriangleShortArrowDown = "",
        TriangleShortArrowLeft = "",
        TriangleShortArrowRight = "",
        TriangleShortArrowUp = "",
        MoonOne = "",
        MoonTwo = "",
        MoonThree = "",
        MoonFour = "",
        MoonFive = "",
        MoonSix = "",
        MoonSeven = "",
        MoonEight = "",
    },
    ---@class diagnostics
    ---@field BoldError string
    ---@field Error string
    ---@field BoldWarning string
    ---@field Warning string
    ---@field BoldInformation string
    ---@field Information string
    ---@field BoldQuestion string
    ---@field Question string
    ---@field BoldHint string
    ---@field Hint string
    ---@field Debug string
    ---@field Trace string
    diagnostics = {
        BoldError = "",
        Error = "",
        BoldWarning = "",
        Warning = "",
        BoldInformation = "",
        Information = "",
        BoldQuestion = "",
        Question = "",
        BoldHint = "",
        Hint = "",
        Debug = "",
        Trace = "✎",
    },
    ---@class misc
    ---@field Robot string
    ---@field Squirrel string
    ---@field Tag string
    ---@field Watch string
    ---@field Smiley string
    ---@field Package string
    ---@field CircuitBoard string
    ---@field Stars string
    misc = {
        Robot = "ﮧ",
        Squirrel = "",
        Tag = "",
        Watch = "",
        Smiley = "",
        Package = "",
        CircuitBoard = "",
        Stars = "",
    },
    ---@class signs
    ---@field ABoxFull string
    ---@field ABoxOutline string
    ---@field ACircleFull string
    ---@field ACircleOutline string
    ---@field BBoxFull string
    ---@field BBoxOutline string
    ---@field BCircleFull string
    ---@field BCircleOutline string
    ---@field CBoxFull string
    ---@field CBoxOutline string
    ---@field CCircleFull string
    ---@field CCircleOutline string
    ---@field DBoxFull string
    ---@field DBoxOutline string
    ---@field DCircleFull string
    ---@field DCircleOutline string
    ---@field EBoxFull string
    ---@field EBoxOutline string
    ---@field ECircleFull string
    ---@field ECircleOutline string
    ---@field FBoxFull string
    ---@field FBoxOutline string
    ---@field FCircleFull string
    ---@field FCircleOutline string
    ---@field GBoxFull string
    ---@field GBoxOutline string
    ---@field GCircleFull string
    ---@field GCircleOutline string
    ---@field HBoxFull string
    ---@field HBoxOutline string
    ---@field HCircleFull string
    ---@field HCircleOutline string
    ---@field IBoxFull string
    ---@field IBoxOutline string
    ---@field ICircleFull string
    ---@field ICircleOutline string
    ---@field JBoxFull string
    ---@field JBoxOutline string
    ---@field JCircleFull string
    ---@field JCircleOutline string
    ---@field KBoxFull string
    ---@field KBoxOutline string
    ---@field KCircleFull string
    ---@field KCircleOutline string
    ---@field LBoxFull string
    ---@field LBoxOutline string
    ---@field LCircleFull string
    ---@field LCircleOutline string
    ---@field MBoxFull string
    ---@field MBoxOutline string
    ---@field MCircleFull string
    ---@field MCircleOutline string
    ---@field NBoxFull string
    ---@field NBoxOutline string
    ---@field NCircleFull string
    ---@field NCircleOutline string
    ---@field OBoxFull string
    ---@field OBoxOutline string
    ---@field OCircleFull string
    ---@field OCircleOutline string
    ---@field PBoxFull string
    ---@field PBoxOutline string
    ---@field PCircleFull string
    ---@field PCircleOutline string
    ---@field QBoxFull string
    ---@field QBoxOutline string
    ---@field QCircleFull string
    ---@field QCircleOutline string
    ---@field RBoxFull string
    ---@field RBoxOutline string
    ---@field RCircleFull string
    ---@field RCircleOutline string
    ---@field SBoxFull string
    ---@field SBoxOutline string
    ---@field SCircleFull string
    ---@field SCircleOutline string
    ---@field TBoxFull string
    ---@field TBoxOutline string
    ---@field TCircleFull string
    ---@field TCircleOutline string
    ---@field UBoxFull string
    ---@field UBoxOutline string
    ---@field UCircleFull string
    ---@field UCircleOutline string
    ---@field VBoxFull string
    ---@field VBoxOutline string
    ---@field VCircleFull string
    ---@field VCircleOutline string
    ---@field WBoxFull string
    ---@field WBoxOutline string
    ---@field WCircleFull string
    ---@field WCircleOutline string
    ---@field XBoxFull string
    ---@field XBoxOutline string
    ---@field XCircleFull string
    ---@field XCircleOutline string
    ---@field YBoxFull string
    ---@field YBoxOutline string
    ---@field YCircleFull string
    ---@field YCircleOutline string
    ---@field ZBoxFull string
    ---@field ZBoxOutline string
    ---@field ZCircleFull string
    ---@field ZCircleOutline string
    signs = {
        A = "󰫮",
        ABoxFull = "󰬈",
        ABoxOutline = "󰯫",
        ACircleFull = "󰯬",
        ACircleOutline = "󰯭",
        B = "󰫯",
        BBoxFull = "󰬉",
        BBoxOutline = "󰯮",
        BCircleFull = "󰯯",
        BCircleOutline = "󰯰",
        C = "󰫰",
        CBoxFull = "󰬊",
        CBoxOutline = "󰯱",
        CCircleFull = "󰯲",
        CCircleOutline = "󰯳",
        D = "󰫱",
        DBoxFull = "󰬋",
        DBoxOutline = "󰯴",
        DCircleFull = "󰯵",
        DCircleOutline = "󰯶",
        E = "󰫲",
        EBoxFull = "󰬌",
        EBoxOutline = "󰯷",
        ECircleFull = "󰯸",
        ECircleOutline = "󰯹",
        F = "󰫳",
        FBoxFull = "󰬍",
        FBoxOutline = "󰯺",
        FCircleFull = "󰯻",
        FCircleOutline = "󰯼",
        G = "󰫴",
        GBoxFull = "󰬎",
        GBoxOutline = "󰯽",
        GCircleFull = "󰯾",
        GCircleOutline = "󰯿",
        H = "󰫵",
        HBoxFull = "󰬏",
        HBoxOutline = "󰰀",
        HCircleFull = "󰰁",
        HCircleOutline = "󰰂",
        I = "󱂈",
        IBoxFull = "󰬐",
        IBoxOutline = "󰰃",
        ICircleFull = "󰰄",
        ICircleOutline = "󰰅",
        J = "󰫷",
        JBoxFull = "󰬑",
        JBoxOutline = "󰰆",
        JCircleFull = "󰰇",
        JCircleOutline = "󰰈",
        K = "󰫸",
        KBoxFull = "󰬒",
        KBoxOutline = "󰰉",
        KCircleFull = "󰰊",
        KCircleOutline = "󰰋",
        L = "󱎦",
        LBoxFull = "󰬓",
        LBoxOutline = "󰰌",
        LCircleFull = "󰰍",
        LCircleOutline = "󰰎",
        M = "󰫺",
        MBoxFull = "󰬔",
        MBoxOutline = "󰰏",
        MCircleFull = "󰰐",
        MCircleOutline = "󰰑",
        N = "󰫻",
        NBoxFull = "󰬕",
        NBoxOutline = "󰰒",
        NCircleFull = "󰰓",
        NCircleOutline = "󰰔",
        O = "󰬹",
        OBoxFull = "󰬖",
        OBoxOutline = "󰰕",
        OCircleFull = "󰲞",
        OCircleOutline = "󰲟",
        P = "󰫽",
        PBoxFull = "󰬗",
        PBoxOutline = "󰰘",
        PCircleFull = "󰰙",
        PCircleOutline = "󰰚",
        Q = "󰫾",
        QBoxFull = "󰬘",
        QBoxOutline = "󰰛",
        QCircleFull = "󰰜",
        QCircleOutline = "󰰝",
        R = "󰫿",
        RBoxFull = "󰬙",
        RBoxOutline = "󰰞",
        RCircleFull = "󰰟",
        RCircleOutline = "󰰠",
        S = "󰬀",
        SBoxFull = "󰬚",
        SBoxOutline = "󰰡",
        SCircleFull = "󰰢",
        SCircleOutline = "󰰣",
        T = "󰬁",
        TBoxFull = "󰬛",
        TBoxOutline = "󰰤",
        TCircleFull = "󰰥",
        TCircleOutline = "󰰦",
        U = "󰬂",
        UBoxFull = "󰬜",
        UBoxOutline = "󰰧",
        UCircleFull = "󰰨",
        UCircleOutline = "󰰩",
        V = "󱂌",
        VBoxFull = "󰬝",
        VBoxOutline = "󰰪",
        VCircleFull = "󰰫",
        VCircleOutline = "󰰬",
        W = "󰬄",
        WBoxFull = "󰬞",
        WBoxOutline = "󰰭",
        WCircleFull = "󰰮",
        WCircleOutline = "󰰯",
        X = "󱂑",
        XBoxFull = "󰬟",
        XBoxOutline = "󰰰",
        XCircleFull = "󰰱",
        XCircleOutline = "󰰲",
        Y = "󰬆",
        YBoxFull = "󰬠",
        YBoxOutline = "󰰳",
        YCircleFull = "󰰴",
        YCircleOutline = "󰰵",
        Z = "󰬇",
        ZBoxFull = "󰬡",
        ZBoxOutline = "󰰶",
        ZCircleFull = "󰰷",
        ZCircleOutline = "󰰸",
    },
}
